# Apache TomEE JAX-RS Starter Project

Know JAX-RS, but haven't yet dug into Apache TomEE?  Way too busy or impatient to read documentation?  This repo is for you.

The only thing better than a Maven archetype is a repo you can fork with everything already setup.  Skip the documentation and just fork-and-code.  This starter project contains:

 - 1 JAX-RS class, 1 JAXB class and 1 JUnit/Arquillian test
 - Maven pom for building a war file
 - Arquillian setup for testing against TomEE JAX-RS Embedded
 - TomEE Maven Plugin for deploying and running our war file

Everything ready-to-run with a simple `mvn clean install tomee:run`

Delete the sample code, replace with your own and you're good to go.

Have time for some reading and curious on how everything works?  [Read here](http://www.tomitribe.com/blog/2014/06/apache-tomee-jax-rs-and-arquillian-starter-project/).

# Uber Jar

If you'd like to build an uber-jar from the project, simply do:

----
mvn clean install tomee:exec
java -jar target/tomee-rest-arquillian-1.0-SNAPSHOT-exec.jar
----
